export const DESC_2: Record<string, string> = {
  // Thú y
  "thu-y": "Đào tạo Bác sĩ thú y chẩn đoán, điều trị bệnh cho động vật.",
  "chan-nuoi": "Kỹ thuật chăn nuôi gia súc, gia cầm quy mô công nghiệp.",
  "chan-nuoi-thu-y": "Kết hợp kỹ thuật chăn nuôi và thú y trong sản xuất nông nghiệp.",
  // Công an - Quân đội
  "cong-an": "Đào tạo sĩ quan công an bảo vệ an ninh trật tự xã hội.",
  "canh-sat": "Đào tạo cảnh sát điều tra, phòng chống tội phạm.",
  "pccc": "Đào tạo lực lượng phòng cháy chữa cháy và cứu hộ cứu nạn.",
  "kt-quan-su": "Đào tạo sĩ quan kỹ thuật vũ khí, khí tài quân đội.",
  "quan-y": "Đào tạo bác sĩ quân y phục vụ lực lượng vũ trang.",
  "chi-huy-tm": "Đào tạo sĩ quan chỉ huy tham mưu tác chiến.",
  "trinh-sat": "Đào tạo chuyên gia trinh sát kỹ thuật và tình báo.",
  // Thiết kế đồ họa
  "thiet-ke-do-hoa": "Thiết kế hình ảnh, logo, bộ nhận diện thương hiệu.",
  "thiet-ke-game": "Thiết kế nhân vật, bối cảnh và trải nghiệm trong game.",
  "tk-da-phuong-tien": "Thiết kế cho nền tảng số: web, app, video, interactive media.",
  "animation": "Sản xuất phim hoạt hình 2D/3D và motion graphics.",
  "ux-ui": "Thiết kế giao diện và trải nghiệm người dùng cho ứng dụng số.",
  "my-thuat-ung-dung": "Ứng dụng mỹ thuật vào đời sống: đồ họa, nội thất, sản phẩm.",
  // Xây dựng - Kiến trúc
  "kien-truc": "Thiết kế công trình kiến trúc kết hợp nghệ thuật và kỹ thuật.",
  "xay-dung": "Thi công, giám sát và quản lý dự án xây dựng.",
  "xd-dan-dung": "Thiết kế và thi công nhà ở, văn phòng, chung cư.",
  "quy-hoach": "Quy hoạch không gian đô thị, vùng lãnh thổ bền vững.",
  "cau-duong": "Thiết kế và xây dựng cầu, đường giao thông.",
  "giao-thong": "Quy hoạch và xây dựng hệ thống giao thông vận tải.",
  "ha-tang": "Xây dựng hạ tầng kỹ thuật: cấp thoát nước, điện, viễn thông.",
  "noi-that": "Thiết kế không gian nội thất nhà ở, văn phòng, thương mại.",
  "cn-xay-dung": "Ứng dụng công nghệ mới trong thi công xây dựng.",
  "canh-quan": "Thiết kế cảnh quan sân vườn, công viên và không gian xanh.",
  // Ngoại ngữ
  "ngon-ngu-anh": "Sử dụng thành thạo tiếng Anh, kỹ năng biên phiên dịch chuyên nghiệp.",
  "ngon-ngu-nhat": "Thành thạo tiếng Nhật, hiểu văn hóa Nhật Bản, cơ hội sang Nhật.",
  "ngon-ngu-han": "Thành thạo tiếng Hàn, cơ hội làm việc tại Hàn Quốc.",
  "ngon-ngu-trung": "Thành thạo tiếng Trung Quốc, thông dịch thương mại Việt-Trung.",
  "ngon-ngu-phap": "Thành thạo tiếng Pháp, cơ hội du học và làm việc tại Pháp.",
  "ngon-ngu-duc": "Thành thạo tiếng Đức, cơ hội du học Đức miễn học phí.",
  "ngon-ngu-nga": "Thành thạo tiếng Nga, hợp tác năng lượng và quốc phòng.",
  "ngon-ngu-tbn": "Thành thạo tiếng Tây Ban Nha - ngôn ngữ phổ biến thứ 2 thế giới.",
  "phien-dich": "Đào tạo phiên dịch viên chuyên nghiệp đa ngôn ngữ.",
  "bien-phien-dich": "Biên dịch văn bản và phiên dịch hội nghị chuyên nghiệp.",
  "quoc-te-hoc": "Nghiên cứu quan hệ quốc tế, chính trị và an ninh toàn cầu.",
  "dong-phuong-hoc": "Nghiên cứu văn hóa, ngôn ngữ các nước Đông Á và Đông Nam Á.",
  "ngoai-giao": "Đào tạo cán bộ ngoại giao, đại diện VN trên trường quốc tế.",
  "ngon-ngu-bo-dao-nha": "Thành thạo tiếng Bồ Đào Nha, kết nối thị trường Brazil.",
  // Ngoại thương
  "ngoai-thuong": "Quản lý hoạt động xuất nhập khẩu và giao thương quốc tế.",
  "xuat-nhap-khau": "Nghiệp vụ hải quan, khai báo xuất nhập khẩu, logistics quốc tế.",
  "kd-quoc-te": "Kinh doanh xuyên biên giới, chiến lược mở rộng thị trường quốc tế.",
  "chuoi-cung-ung": "Quản trị chuỗi cung ứng toàn cầu từ nhà cung cấp đến người tiêu dùng.",
  "hai-quan": "Nghiệp vụ hải quan, kiểm tra hàng hóa xuất nhập khẩu.",
  "kt-quoc-te": "Phân tích kinh tế quốc tế, cán cân thương mại và tỷ giá.",
  // Du lịch
  "du-lich": "Quản lý và phát triển sản phẩm du lịch, điểm đến.",
  "qt-khach-san": "Quản lý vận hành khách sạn, resort theo tiêu chuẩn quốc tế.",
  "qt-nha-hang": "Quản lý nhà hàng, dịch vụ ẩm thực và ăn uống.",
  "dv-du-lich": "Tổ chức tour, dịch vụ lữ hành trong nước và quốc tế.",
  "huong-dan-dl": "Hướng dẫn khách du lịch tham quan, thuyết minh di tích.",
  "qt-le-tan": "Nghiệp vụ lễ tân khách sạn, quản lý đặt phòng và dịch vụ.",
  "vn-hoc": "Nghiên cứu văn hóa, lịch sử VN ứng dụng vào du lịch.",
  // Ô tô - Cơ khí
  "ky-thuat-o-to": "Thiết kế, chế tạo và bảo dưỡng hệ thống ô tô hiện đại.",
  "co-khi": "Thiết kế, gia công và chế tạo chi tiết máy, thiết bị cơ khí.",
  "co-dien-tu": "Kết hợp cơ khí, điện tử và CNTT trong hệ thống tự động.",
  "che-tao": "Công nghệ gia công, chế tạo sản phẩm cơ khí chính xác.",
  "kt-nhiet": "Thiết kế hệ thống nhiệt: điều hòa, lò hơi, trao đổi nhiệt.",
  "cn-co-khi": "Ứng dụng công nghệ vào sản xuất và gia công cơ khí.",
  "cn-oto": "Công nghệ sửa chữa, bảo dưỡng và kiểm định ô tô.",
  "kt-cong-nghiep": "Tối ưu hóa quy trình sản xuất và quản lý nhà máy.",
  "che-tao-may": "Thiết kế và chế tạo máy móc công nghiệp.",
  // Điện - Tự động hóa
  "kt-dien": "Thiết kế hệ thống điện: nhà máy điện, truyền tải, phân phối.",
  "dien-tu-vien-thong": "Thiết kế mạch điện tử và hệ thống viễn thông.",
  "tu-dong-hoa": "Thiết kế hệ thống điều khiển tự động trong công nghiệp.",
  "kt-dien-tu": "Thiết kế vi mạch, mạch điện tử ứng dụng.",
  "cn-dien": "Ứng dụng công nghệ trong lắp đặt và vận hành hệ thống điện.",
  "cn-dien-tu": "Lắp ráp, sửa chữa và bảo trì thiết bị điện tử.",
  "dien-lanh": "Thiết kế và vận hành hệ thống lạnh, điều hòa không khí.",
  "vien-thong": "Thiết kế và vận hành mạng viễn thông: 4G/5G, cáp quang.",
  "he-thong-dien": "Vận hành và bảo trì hệ thống điện lực quốc gia.",
  // Hàng hải
  "dieu-khien-tau": "Điều khiển tàu biển, hải hành và quản lý hàng hóa trên tàu.",
  "tau-thuy": "Thiết kế và đóng mới tàu thủy dân dụng và quân sự.",
  "thuy-loi": "Thiết kế hệ thống thủy lợi: đê, đập, kênh mương.",
  "kt-bien": "Khai thác tài nguyên biển và xây dựng công trình ven biển.",
  "khi-tuong": "Dự báo thời tiết, theo dõi biến đổi khí hậu.",
  "kt-van-tai-bien": "Quản lý kinh tế vận tải và thương mại hàng hải.",
  "logistics-hh": "Quản lý chuỗi logistics đường biển và cảng.",
  // Hàng không
  "hang-khong": "Thiết kế, chế tạo và bảo dưỡng máy bay.",
  "vu-tru": "Nghiên cứu công nghệ vũ trụ, vệ tinh và tên lửa.",
  "hat-nhan": "Ứng dụng năng lượng hạt nhân và kỹ thuật bức xạ.",
  "ql-bay": "Quản lý không lưu, điều phối hoạt động bay.",
  "phi-cong": "Đào tạo phi công thương mại điều khiển máy bay dân dụng.",
  "kt-may-bay": "Bảo dưỡng, sửa chữa và kiểm tra kỹ thuật máy bay.",
  // Vật liệu
  "vat-lieu": "Nghiên cứu và phát triển vật liệu mới cho công nghiệp.",
  "vat-lieu-kim-loai": "Luyện kim, gia công và xử lý nhiệt kim loại.",
  "vat-lieu-polyme": "Nghiên cứu nhựa, composite và vật liệu polymer.",
  "vat-lieu-silicat": "Sản xuất gốm sứ, thủy tinh, xi măng và gạch.",
  "vat-lieu-dien-tu": "Vật liệu bán dẫn, siêu dẫn cho ngành điện tử.",
  // Thực phẩm
  "cn-thuc-pham": "Chế biến, bảo quản và kiểm soát chất lượng thực phẩm.",
  "dam-bao-cltp": "Kiểm tra an toàn vệ sinh thực phẩm, hệ thống HACCP.",
  "cn-sau-thu-hoach": "Bảo quản và chế biến nông sản sau thu hoạch.",
  "dinh-duong-tp": "Nghiên cứu dinh dưỡng và phát triển sản phẩm thực phẩm chức năng.",
  "cn-che-bien": "Công nghệ chế biến thủy sản, thịt, sữa và đồ uống.",
  // In - Giấy
  "cn-in": "Công nghệ in ấn: in offset, in kỹ thuật số, in bao bì.",
  "cn-giay-bao-bi": "Sản xuất giấy, bao bì và bìa carton công nghiệp.",
  // Sinh - Hóa
  "cn-sinh-hoc": "Ứng dụng sinh học vào y dược, nông nghiệp, môi trường.",
  "hoa-hoc": "Nghiên cứu cơ bản về hóa học: hữu cơ, vô cơ, phân tích.",
  "hoa-duoc": "Nghiên cứu và phát triển thuốc mới, dược phẩm.",
  "cn-hoa-hoc": "Ứng dụng hóa học trong sản xuất công nghiệp.",
  "hoa-phan-tich": "Phân tích thành phần hóa học của mẫu vật trong phòng thí nghiệm.",
  "sinh-hoc": "Nghiên cứu các hệ thống sống từ phân tử đến hệ sinh thái.",
  "sinh-hoc-ung-dung": "Ứng dụng sinh học vào sản xuất và đời sống.",
  "hoa-hoc-ung-dung": "Ứng dụng hóa học vào mỹ phẩm, thực phẩm, vật liệu.",
  "vi-sinh-vat": "Nghiên cứu vi khuẩn, virus, nấm ứng dụng trong y dược, nông nghiệp.",
  // Luật
  "luat": "Đào tạo luật sư, thẩm phán và chuyên gia pháp lý.",
  "luat-kinh-te": "Tư vấn pháp lý cho doanh nghiệp, hợp đồng thương mại.",
  "luat-quoc-te": "Luật pháp quốc tế, công pháp và tư pháp quốc tế.",
  "luat-thuong-mai": "Pháp luật thương mại quốc tế, WTO, FTA.",
  "luat-dan-su": "Giải quyết tranh chấp dân sự, gia đình, thừa kế.",
  "luat-hinh-su": "Tội phạm học, luật hình sự và tố tụng hình sự.",
  "luat-hanh-chinh": "Pháp luật hành chính và quản lý nhà nước.",
  // Mỏ - Địa chất
  "dia-chat": "Nghiên cứu cấu trúc Trái Đất, khoáng sản và địa tầng.",
  "kt-dia-chat": "Khảo sát, thăm dò địa chất phục vụ xây dựng và khai thác.",
  "kt-mo": "Khai thác khoáng sản: than, quặng, vật liệu xây dựng.",
  "kt-dau-khi": "Thăm dò và khai thác dầu khí ngoài khơi.",
  "trac-dia": "Đo đạc, lập bản đồ địa hình và hệ thống GIS.",
  // Mỹ thuật - Âm nhạc
  "my-thuat": "Nghiên cứu mỹ thuật tạo hình: hội họa, điêu khắc, đồ họa.",
  "am-nhac": "Nghiên cứu lý thuyết âm nhạc, sáng tác và phê bình.",
  "thanh-nhac": "Đào tạo ca sĩ chuyên nghiệp, biểu diễn thanh nhạc.",
  "hoi-hoa": "Sáng tác tranh nghệ thuật: sơn dầu, acrylic, màu nước.",
  "dieu-khac": "Sáng tác tác phẩm điêu khắc từ đá, gỗ, kim loại.",
  "san-khau-dien-anh": "Đạo diễn, biên kịch và sản xuất phim điện ảnh.",
  "nhac-cu": "Biểu diễn chuyên nghiệp nhạc cụ: piano, violin, guitar.",
  "nghe-thuat-truyen-thong": "Bảo tồn và phát triển nghệ thuật dân gian truyền thống.",
  // Tài nguyên - Môi trường
  "khoa-hoc-mt": "Nghiên cứu hệ sinh thái, ô nhiễm và bảo vệ môi trường.",
  "cn-ky-thuat-mt": "Xử lý nước thải, khí thải và chất thải rắn.",
  "kt-moi-truong": "Thiết kế hệ thống xử lý môi trường cho nhà máy, khu công nghiệp.",
  "ql-tai-nguyen": "Quản lý khai thác và bảo tồn tài nguyên thiên nhiên.",
  "ql-dat-dai": "Đăng ký, quản lý và quy hoạch sử dụng đất.",
  "bien-doi-khi-hau": "Nghiên cứu và ứng phó với biến đổi khí hậu toàn cầu.",
  "ql-bien": "Quản lý tài nguyên biển, hải đảo và vùng ven biển.",
  // Tâm lý
  "tam-ly-hoc": "Nghiên cứu hành vi, nhận thức và cảm xúc con người.",
  "tam-ly-lam-sang": "Đánh giá, chẩn đoán và trị liệu các rối loạn tâm lý.",
  // Thể thao
  "huan-luyen": "Huấn luyện vận động viên chuyên nghiệp các bộ môn.",
  "giao-duc-tc": "Giáo dục thể chất và tổ chức hoạt động thể thao.",
  "quan-ly-tt": "Quản lý câu lạc bộ, sự kiện và tổ chức thể thao.",
  // Thời trang
  "thiet-ke-thoi-trang": "Sáng tạo bộ sưu tập, thiết kế mẫu quần áo.",
  "cn-may": "Công nghệ may công nghiệp: rập, cắt, may, hoàn thiện.",
  "cn-det": "Sản xuất vải dệt thoi, dệt kim phục vụ ngành may.",
  "cn-soi": "Sản xuất sợi tự nhiên và sợi tổng hợp cho ngành dệt.",
  "cn-da-giay": "Sản xuất giày dép và sản phẩm da.",
  // Nông Lâm Thủy sản
  "nong-nghiep": "Kỹ thuật trồng trọt, canh tác nông nghiệp hiện đại.",
  "lam-nghiep": "Quản lý, bảo vệ và phát triển rừng bền vững.",
  "thuy-san": "Nuôi trồng tôm, cá và hải sản quy mô công nghiệp.",
  "bvtv": "Phòng trừ sâu bệnh hại cây trồng bằng biện pháp tổng hợp.",
  "khoa-hoc-cay-trong": "Nghiên cứu giống, sinh lý và dinh dưỡng cây trồng.",
  "nong-hoc": "Khoa học nông nghiệp tổng hợp: đất, nước, cây, phân bón.",
  "cong-nghe-rau-hoa": "Sản xuất rau, hoa, quả sạch theo tiêu chuẩn VietGAP, GlobalGAP.",
  "lam-sinh": "Trồng rừng, phục hồi rừng và kinh doanh lâm sản.",
  "ql-tn-rung": "Quản lý tài nguyên rừng, đa dạng sinh học.",
  "che-bien-thuy-san": "Chế biến tôm, cá xuất khẩu theo tiêu chuẩn quốc tế.",
  // Toán - Thống kê
  "toan-hoc": "Nghiên cứu toán học thuần túy: đại số, giải tích, hình học.",
  "toan-ung-dung": "Ứng dụng toán học vào khoa học, kỹ thuật và kinh tế.",
  "thong-ke-hoc": "Phương pháp thống kê, phân tích dữ liệu và xác suất.",
  "toan-tin": "Kết hợp toán học và tin học: thuật toán, mật mã.",
  "khoa-hoc-tinh-toan": "Mô phỏng số và tính toán hiệu năng cao.",
  // Nhân sự
  "quan-tri-ns": "Tuyển dụng, đào tạo, đánh giá nhân viên trong tổ chức.",
  "hanh-chinh-hoc": "Quản lý hành chính nhà nước và tổ chức công.",
  "quan-ly-cong": "Quản lý khu vực công: chính sách, ngân sách, dịch vụ.",
  "chinh-sach-cong": "Phân tích và hoạch định chính sách công cho xã hội.",
  "van-thu-luu-tru": "Quản lý văn bản, hồ sơ và hệ thống lưu trữ tổ chức.",
  // Văn hóa - Xã hội
  "xa-hoi-hoc": "Nghiên cứu các hiện tượng xã hội, bất bình đẳng và biến đổi xã hội.",
  "cong-tac-xa-hoi": "Hỗ trợ nhóm yếu thế: trẻ em, người già, người khuyết tật.",
  "van-hoc": "Nghiên cứu và sáng tác văn học Việt Nam và thế giới.",
  "lich-su": "Nghiên cứu lịch sử dân tộc và thế giới.",
  "triet-hoc": "Nghiên cứu tư tưởng triết học phương Đông và phương Tây.",
  "chinh-tri-hoc": "Nghiên cứu hệ thống chính trị, nhà nước và đảng phái.",
  "quan-he-quoc-te": "Phân tích quan hệ giữa các quốc gia và tổ chức quốc tế.",
  "bao-tang-hoc": "Bảo tồn, trưng bày và quản lý di sản văn hóa.",
  "nhan-hoc": "Nghiên cứu con người: văn hóa, tộc người, xã hội.",
  "viet-nam-hoc": "Nghiên cứu tổng hợp về đất nước, con người và văn hóa VN.",
  // Khoa học tự nhiên
  "vat-ly": "Nghiên cứu vật lý lý thuyết và thực nghiệm.",
  "thien-van": "Nghiên cứu vũ trụ, thiên thể và vật lý thiên văn.",
};

// Subject overrides phần 2
export const SUBJ_OVERRIDE_2: Record<string, string[]> = {
  "ngon-ngu-nhat": ["D01","D06"],
  "ngon-ngu-han": ["D01","D06"],
  "ngon-ngu-trung": ["D01","D04"],
  "ngon-ngu-phap": ["D01","D03"],
  "ngon-ngu-duc": ["D01","D05"],
  "ngon-ngu-nga": ["D01","D02"],
  "ngon-ngu-tbn": ["D01"],
  "ngon-ngu-bo-dao-nha": ["D01"],
  "noi-that": ["V00","V01","H01"],
  "kien-truc": ["V00","V01","H01"],
  "canh-quan": ["V00","V01"],
  "thiet-ke-thoi-trang": ["H00","V00","H01"],
  "san-khau-dien-anh": ["N00","S00"],
  "am-nhac": ["N00","N01"],
  "thanh-nhac": ["N00","N01"],
  "nhac-cu": ["N00","N01"],
  "hoi-hoa": ["H00","H01","V00"],
  "dieu-khac": ["H00","H01"],
  "huan-luyen": ["T00","T01"],
  "quan-ly-tt": ["A00","D01","T00"],
};
