// slug → description ngắn cho từng ngành
export const DESC_1: Record<string, string> = {
  // Kế toán
  "ke-toan": "Đào tạo chuyên gia kế toán, kiểm toán với kiến thức tài chính, thuế và kiểm soát nội bộ.",
  "kiem-toan": "Đào tạo chuyên gia kiểm tra, đánh giá tính trung thực của báo cáo tài chính doanh nghiệp.",
  "ke-toan-cong": "Chuyên về kế toán trong khu vực công: ngân sách nhà nước, đơn vị hành chính sự nghiệp.",
  // Tài chính - Ngân hàng
  "tai-chinh-ngan-hang": "Đào tạo chuyên gia tài chính, tín dụng và quản lý rủi ro trong hệ thống ngân hàng.",
  "bao-hiem": "Nghiên cứu và ứng dụng các sản phẩm bảo hiểm nhân thọ, phi nhân thọ và tái bảo hiểm.",
  "tai-chinh-cong": "Quản lý tài chính nhà nước: ngân sách, thuế, chi tiêu công và nợ công.",
  "chung-khoan": "Phân tích, đầu tư và quản lý danh mục chứng khoán trên thị trường vốn.",
  "tai-chinh-dn": "Quản lý tài chính doanh nghiệp: huy động vốn, đầu tư và phân phối lợi nhuận.",
  "ngan-hang": "Vận hành nghiệp vụ ngân hàng: cho vay, huy động, thanh toán quốc tế.",
  "dau-tu": "Phân tích và ra quyết định đầu tư vào các loại tài sản tài chính và dự án.",
  "phan-tich-tc": "Sử dụng dữ liệu tài chính để đánh giá hiệu quả và dự báo xu hướng kinh doanh.",
  "fintech": "Ứng dụng công nghệ số vào dịch vụ tài chính: ví điện tử, blockchain, lending.",
  // Kinh tế - QTKD
  "quan-tri-kinh-doanh": "Kiến thức toàn diện về quản trị doanh nghiệp: nhân sự, tài chính, marketing, chuỗi cung ứng.",
  "kinh-te": "Nghiên cứu quy luật kinh tế vĩ mô, vi mô và chính sách phát triển.",
  "kinh-te-quoc-te": "Phân tích quan hệ kinh tế giữa các quốc gia, thương mại và đầu tư quốc tế.",
  "kinh-doanh-quoc-te": "Quản trị hoạt động kinh doanh xuyên biên giới và chiến lược toàn cầu hóa.",
  "marketing": "Nghiên cứu thị trường, xây dựng thương hiệu và chiến lược tiếp thị sản phẩm.",
  "tmdt": "Kinh doanh trên nền tảng số: e-commerce, digital marketing, quản lý sàn giao dịch.",
  "quan-tri-nhan-luc": "Tuyển dụng, đào tạo, đánh giá và phát triển nguồn nhân lực trong tổ chức.",
  "logistics": "Quản lý chuỗi cung ứng, kho bãi, vận tải và phân phối hàng hóa.",
  "kinh-doanh-so": "Ứng dụng công nghệ số vào mô hình kinh doanh và chuyển đổi số doanh nghiệp.",
  "kinh-te-phat-trien": "Nghiên cứu chiến lược phát triển kinh tế bền vững cho các quốc gia và vùng lãnh thổ.",
  "kinh-te-dau-tu": "Phân tích và thẩm định dự án đầu tư, quản lý danh mục đầu tư.",
  "thong-ke": "Ứng dụng phương pháp thống kê vào phân tích dữ liệu kinh tế và xã hội.",
  "kinh-te-chinh-tri": "Nghiên cứu mối quan hệ giữa kinh tế, chính trị và thể chế nhà nước.",
  "thuong-mai": "Quản lý hoạt động mua bán hàng hóa, dịch vụ trong nước và quốc tế.",
  "quan-tri-cong-nghiep": "Tối ưu hóa quy trình sản xuất, quản lý chất lượng trong nhà máy.",
  "httt-quan-ly": "Thiết kế và vận hành hệ thống thông tin phục vụ quản lý doanh nghiệp.",
  "kinh-te-so": "Nghiên cứu nền kinh tế dựa trên dữ liệu, nền tảng số và AI.",
  "khoi-nghiep": "Phát triển tư duy khởi nghiệp, xây dựng mô hình kinh doanh và gọi vốn.",
  "kinh-te-lao-dong": "Nghiên cứu thị trường lao động, tiền lương và chính sách việc làm.",
  "bat-dong-san": "Định giá, môi giới, quản lý và đầu tư bất động sản.",
  "quan-tri-van-phong": "Quản lý hành chính văn phòng, lễ tân, lưu trữ và tổ chức sự kiện.",
  "quan-tri-du-an": "Lập kế hoạch, điều phối nguồn lực và kiểm soát tiến độ dự án.",
  // CNTT
  "cong-nghe-thong-tin": "Ngành học về máy tính, phần mềm, mạng và hệ thống phân phối dữ liệu.",
  "khoa-hoc-may-tinh": "Nghiên cứu nền tảng lý thuyết và thuật toán của khoa học máy tính.",
  "ky-thuat-phan-mem": "Quy trình phát triển phần mềm chuyên nghiệp từ phân tích đến triển khai.",
  "he-thong-thong-tin": "Thiết kế và quản lý hệ thống thông tin phục vụ tổ chức và doanh nghiệp.",
  "mang-may-tinh": "Thiết kế, triển khai và bảo trì hạ tầng mạng máy tính.",
  "tri-tue-nhan-tao": "Nghiên cứu và phát triển các hệ thống AI: machine learning, deep learning, NLP.",
  "khoa-hoc-du-lieu": "Thu thập, xử lý và phân tích dữ liệu lớn để tạo ra insights kinh doanh.",
  "an-toan-thong-tin": "Bảo vệ hệ thống và dữ liệu khỏi các cuộc tấn công mạng.",
  "cntt-da-phuong-tien": "Kết hợp CNTT với đồ họa, video, âm thanh để tạo sản phẩm đa phương tiện.",
  "he-thong-nhung": "Lập trình và thiết kế các hệ thống nhúng trong thiết bị điện tử.",
  "ky-thuat-may-tinh": "Thiết kế phần cứng máy tính, vi xử lý và hệ thống số.",
  "iot": "Phát triển ứng dụng kết nối vạn vật: cảm biến, gateway, cloud platform.",
  "robot-ai": "Thiết kế robot thông minh kết hợp cơ khí, điện tử và trí tuệ nhân tạo.",
  "phat-trien-game": "Lập trình, thiết kế và phát triển trò chơi điện tử đa nền tảng.",
  "blockchain": "Phát triển ứng dụng phi tập trung trên nền tảng blockchain.",
  "dien-toan-dam-may": "Thiết kế và vận hành hạ tầng điện toán đám mây: AWS, Azure, GCP.",
  "tin-hoc-ung-dung": "Ứng dụng CNTT vào các lĩnh vực cụ thể: giáo dục, y tế, kinh doanh.",
  "cnpm-nhat-ban": "Phát triển phần mềm theo quy trình và văn hóa Nhật Bản, cơ hội việc làm tại Nhật.",
  "thiet-ke-web": "Thiết kế giao diện và trải nghiệm người dùng cho website.",
  "tmdt-cntt": "Xây dựng và vận hành hệ thống thương mại điện tử từ góc độ kỹ thuật.",
  // Bán dẫn
  "thiet-ke-vi-mach": "Thiết kế vi mạch bán dẫn (IC design) sử dụng VHDL, Verilog.",
  "cong-nghe-ban-dan": "Quy trình sản xuất chip bán dẫn: lithography, etching, packaging.",
  "kt-dien-tu-ban-dan": "Kỹ thuật điện tử ứng dụng trong công nghiệp bán dẫn.",
  "vat-lieu-ban-dan": "Nghiên cứu vật liệu silicon, GaN, SiC cho ngành bán dẫn.",
  "vi-dien-tu": "Thiết kế và chế tạo linh kiện vi điện tử ở quy mô nano.",
  // Báo chí - Marketing
  "bao-chi": "Đào tạo nhà báo chuyên nghiệp: viết tin, phóng sự, điều tra.",
  "truyen-thong-da-pt": "Sản xuất nội dung đa nền tảng: video, podcast, social media.",
  "pr": "Xây dựng và bảo vệ hình ảnh thương hiệu, quản lý truyền thông khủng hoảng.",
  "quang-cao": "Sáng tạo và triển khai chiến dịch quảng cáo đa kênh.",
  "truyen-thong-dn": "Quản lý truyền thông nội bộ và bên ngoài cho doanh nghiệp.",
  "bao-chi-truyen-hinh": "Sản xuất chương trình truyền hình: biên tập, dẫn chương trình, kỹ thuật.",
  "xuat-ban": "Biên tập, xuất bản sách và ấn phẩm số.",
  "truyen-thong-qt": "Truyền thông và quan hệ quốc tế trong bối cảnh toàn cầu hóa.",
  "marketing-so": "Tiếp thị kỹ thuật số: SEO, SEM, social media marketing, content marketing.",
  "noi-dung-so": "Sáng tạo nội dung cho nền tảng số: TikTok, YouTube, blog.",
  // Sư phạm
  "sp-toan": "Đào tạo giáo viên Toán THPT với năng lực sư phạm và chuyên môn vững.",
  "sp-ngu-van": "Đào tạo giáo viên Ngữ văn, truyền cảm hứng văn học cho học sinh.",
  "sp-tieng-anh": "Đào tạo giáo viên Tiếng Anh đạt chuẩn quốc tế.",
  "sp-vat-ly": "Đào tạo giáo viên Vật lý với khả năng thí nghiệm và giảng dạy sáng tạo.",
  "sp-hoa-hoc": "Đào tạo giáo viên Hóa học THPT.",
  "sp-sinh-hoc": "Đào tạo giáo viên Sinh học với kiến thức thực nghiệm.",
  "sp-lich-su": "Đào tạo giáo viên Lịch sử, truyền tải bài học từ quá khứ.",
  "sp-dia-ly": "Đào tạo giáo viên Địa lý với kiến thức địa lý tự nhiên và kinh tế.",
  "sp-tin-hoc": "Đào tạo giáo viên Tin học, giảng dạy lập trình và kỹ năng số.",
  "sp-mam-non": "Đào tạo giáo viên mầm non chăm sóc và giáo dục trẻ 0-6 tuổi.",
  "sp-tieu-hoc": "Đào tạo giáo viên tiểu học dạy đa môn cho học sinh lớp 1-5.",
  "gd-the-chat": "Đào tạo giáo viên thể dục và huấn luyện viên thể thao học đường.",
  "gd-quoc-phong": "Đào tạo giáo viên giáo dục quốc phòng an ninh.",
  "gd-chinh-tri": "Đào tạo giáo viên Giáo dục công dân và lý luận chính trị.",
  "gd-dac-biet": "Đào tạo giáo viên dạy trẻ khuyết tật và trẻ có nhu cầu đặc biệt.",
  "sp-am-nhac": "Đào tạo giáo viên Âm nhạc cho trường phổ thông.",
  "sp-my-thuat": "Đào tạo giáo viên Mỹ thuật với kỹ năng hội họa và sáng tạo.",
  "sp-cong-nghe": "Đào tạo giáo viên môn Công nghệ THPT.",
  "khoa-hoc-gd": "Nghiên cứu khoa học giáo dục, phương pháp dạy học hiện đại.",
  "quan-ly-gd": "Quản lý trường học, cơ sở giáo dục và hệ thống giáo dục.",
  // Y - Dược
  "y-khoa": "Đào tạo Bác sĩ y khoa chẩn đoán, điều trị và phòng ngừa bệnh.",
  "rang-ham-mat": "Đào tạo Bác sĩ Răng Hàm Mặt chuyên khoa nha khoa.",
  "y-hoc-co-truyen": "Kết hợp y học phương Đông (châm cứu, thuốc nam) với y học hiện đại.",
  "duoc-hoc": "Đào tạo Dược sĩ về thuốc, dược phẩm, dược lý và hóa dược.",
  "dieu-duong": "Chăm sóc sức khỏe người bệnh, hỗ trợ bác sĩ trong điều trị.",
  "y-hoc-du-phong": "Phòng ngừa dịch bệnh, giám sát sức khỏe cộng đồng.",
  "y-te-cong-cong": "Quản lý hệ thống y tế, chính sách sức khỏe cộng đồng.",
  "xet-nghiem": "Xét nghiệm máu, vi sinh, hóa sinh phục vụ chẩn đoán bệnh.",
  "ho-sinh": "Chăm sóc sức khỏe thai phụ, sản phụ và trẻ sơ sinh.",
  "hinh-anh-y-hoc": "Vận hành thiết bị X-quang, CT, MRI phục vụ chẩn đoán.",
  "phuc-hoi-cn": "Phục hồi chức năng vận động cho bệnh nhân sau chấn thương, đột quỵ.",
  "dinh-duong": "Tư vấn dinh dưỡng, xây dựng chế độ ăn phù hợp cho người bệnh.",
  "quan-ly-bv": "Quản lý vận hành bệnh viện, phòng khám và cơ sở y tế.",
};

// Subject overrides cho ngành đặc thù (khác với template category)
export const SUBJ_OVERRIDE: Record<string, string[]> = {
  "sp-ngu-van": ["C00","D01","D14"],
  "sp-tieng-anh": ["D01","D14","D15"],
  "sp-lich-su": ["C00","D01","C19"],
  "sp-dia-ly": ["C00","A01","D10"],
  "sp-mam-non": ["M00","M01"],
  "sp-tieu-hoc": ["A00","D01","C00"],
  "sp-am-nhac": ["N00","N01"],
  "sp-my-thuat": ["H00","H01","V00"],
  "gd-the-chat": ["T00","T01"],
  "gd-chinh-tri": ["C00","D01","C19"],
  "gd-dac-biet": ["C00","D01"],
  "rang-ham-mat": ["B00","A00"],
  "duoc-hoc": ["B00","A00","D07"],
  "dieu-duong": ["B00","A00"],
  "y-hoc-du-phong": ["B00","A00"],
  "ho-sinh": ["B00"],
  "xet-nghiem": ["B00","A00"],
  "hinh-anh-y-hoc": ["B00","A00"],
  "phuc-hoi-cn": ["B00","A00"],
  "dinh-duong": ["B00","A00","D08"],
  "bao-chi": ["C00","D01","D14"],
  "tmdt": ["A00","A01","D01"],
  "logistics": ["A00","A01","D01","D07"],
};
