/* eslint-disable */
/**
 * Generated `api` utility.
 * 
 * THIS CODE IS AUTOMATICALLY GENERATED.
 * Do NOT edit this file manually.
 * Run `npx convex dev` to regenerate this file.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as majors from "../majors.js";
import type * as quiz from "../quiz.js";
import type * as seed from "../seed.js";

/**
 * A utility for referencing Convex functions in your app's API.
 */
declare const fullApi: ApiFromModules<{
  majors: typeof majors;
  quiz: typeof quiz;
  seed: typeof seed;
}>;
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
